export const mockUser = {
  id: 'usr_1',
  name: 'Alex Johnson',
  email: 'alex@lumabela.com',
  avatar: '',
  level: 12,
  xp: 680,
  xpToNext: 1000,
  streak: 14,
  badges: ['fast-learner', 'quiz-master', 'week-streak', 'first-course', 'ai-explorer', 'social-butterfly'],
  enrolledCourses: 8,
  completedCourses: 3,
  totalHoursLearned: 127,
  rank: 42,
};

export const mockCourses = [
  {
    id: 'cs_1',
    title: 'Advanced React Patterns',
    description: 'Master advanced React patterns including compound components, render props, hooks composition, and state machines for building scalable applications.',
    instructor: 'Sarah Chen',
    instructorAvatar: '',
    thumbnail: '',
    category: 'programming' as const,
    level: 'Advanced',
    duration: '24h',
    lessons: 32,
    enrolled: 15420,
    rating: 4.9,
    progress: 68,
    tags: ['React', 'TypeScript', 'Patterns'],
    isPremium: false,
    lastAccessed: '2 hours ago',
  },
  {
    id: 'cs_2',
    title: 'UI/UX Design Masterclass',
    description: 'Learn professional UI/UX design from wireframing to high-fidelity prototypes. Master Figma, design systems, and user research methodologies.',
    instructor: 'Marcus Rivera',
    instructorAvatar: '',
    thumbnail: '',
    category: 'design' as const,
    level: 'Intermediate',
    duration: '36h',
    lessons: 48,
    enrolled: 22150,
    rating: 4.8,
    progress: 35,
    tags: ['Figma', 'UX Research', 'Design Systems'],
    isPremium: true,
    lastAccessed: '1 day ago',
  },
  {
    id: 'cs_3',
    title: 'Machine Learning Fundamentals',
    description: 'Build a strong foundation in ML with hands-on projects covering supervised learning, neural networks, and model evaluation techniques.',
    instructor: 'Dr. Priya Patel',
    instructorAvatar: '',
    thumbnail: '',
    category: 'data-science' as const,
    level: 'Beginner',
    duration: '40h',
    lessons: 52,
    enrolled: 31200,
    rating: 4.7,
    progress: 12,
    tags: ['Python', 'ML', 'TensorFlow'],
    isPremium: false,
    lastAccessed: '3 days ago',
  },
  {
    id: 'cs_4',
    title: 'Python for Data Science',
    description: 'Comprehensive Python course covering data manipulation, visualization, and analysis with pandas, numpy, and matplotlib.',
    instructor: 'James Wilson',
    instructorAvatar: '',
    thumbnail: '',
    category: 'data-science' as const,
    level: 'Beginner',
    duration: '28h',
    lessons: 36,
    enrolled: 45800,
    rating: 4.9,
    progress: 0,
    tags: ['Python', 'Pandas', 'NumPy'],
    isPremium: false,
    lastAccessed: null,
  },
  {
    id: 'cs_5',
    title: 'Full-Stack TypeScript',
    description: 'End-to-end TypeScript development with Next.js, Prisma, PostgreSQL, and deployment strategies for production applications.',
    instructor: 'Elena Kowalski',
    instructorAvatar: '',
    thumbnail: '',
    category: 'programming' as const,
    level: 'Advanced',
    duration: '48h',
    lessons: 64,
    enrolled: 18900,
    rating: 4.8,
    progress: 0,
    tags: ['TypeScript', 'Next.js', 'PostgreSQL'],
    isPremium: true,
    lastAccessed: null,
  },
  {
    id: 'cs_6',
    title: 'Business Strategy & Innovation',
    description: 'Learn to develop and execute business strategies, understand market dynamics, and drive innovation in competitive landscapes.',
    instructor: 'Michael Torres',
    instructorAvatar: '',
    thumbnail: '',
    category: 'business' as const,
    level: 'Intermediate',
    duration: '20h',
    lessons: 28,
    enrolled: 12400,
    rating: 4.6,
    progress: 0,
    tags: ['Strategy', 'Innovation', 'Leadership'],
    isPremium: false,
    lastAccessed: null,
  },
  {
    id: 'cs_7',
    title: 'Conversational Japanese',
    description: 'Learn Japanese from zero to conversational with immersive lessons covering grammar, vocabulary, kanji, and cultural context.',
    instructor: 'Yuki Tanaka',
    instructorAvatar: '',
    thumbnail: '',
    category: 'language' as const,
    level: 'Beginner',
    duration: '32h',
    lessons: 40,
    enrolled: 9800,
    rating: 4.9,
    progress: 0,
    tags: ['Japanese', 'JLPT', 'Culture'],
    isPremium: true,
    lastAccessed: null,
  },
  {
    id: 'cs_8',
    title: 'Calculus: From Basics to Mastery',
    description: 'Comprehensive calculus course covering limits, derivatives, integrals, and their real-world applications in science and engineering.',
    instructor: 'Dr. Alan Foster',
    instructorAvatar: '',
    thumbnail: '',
    category: 'mathematics' as const,
    level: 'Intermediate',
    duration: '35h',
    lessons: 44,
    enrolled: 15600,
    rating: 4.7,
    progress: 0,
    tags: ['Calculus', 'Mathematics', 'Analysis'],
    isPremium: false,
    lastAccessed: null,
  },
];

export const mockCourseDetails = {
  id: 'cs_1',
  title: 'Advanced React Patterns',
  description: 'Master advanced React patterns including compound components, render props, hooks composition, and state machines for building scalable applications.',
  instructor: 'Sarah Chen',
  instructorAvatar: '',
  category: 'programming',
  level: 'Advanced',
  duration: '24h',
  totalLessons: 32,
  enrolled: 15420,
  rating: 4.9,
  ratingCount: 2847,
  progress: 68,
  tags: ['React', 'TypeScript', 'Patterns'],
  isPremium: false,
  whatYouLearn: [
    'Build scalable React applications with advanced patterns',
    'Master compound components and render props',
    'Implement custom hooks for complex state logic',
    'Design flexible and composable APIs',
    'Optimize performance with advanced techniques',
  ],
  requirements: [
    'Solid understanding of React fundamentals',
    'Experience with hooks and functional components',
    'Basic TypeScript knowledge',
  ],
  modules: [
    {
      id: 'mod_1',
      title: 'Foundations & Philosophy',
      lessons: [
        { id: 'les_1', title: 'Thinking in Patterns', duration: '12m', completed: true, type: 'video' as const },
        { id: 'les_2', title: 'Component API Design', duration: '18m', completed: true, type: 'video' as const },
        { id: 'les_3', title: 'Practice: API Refactoring', duration: '25m', completed: true, type: 'exercise' as const },
      ],
    },
    {
      id: 'mod_2',
      title: 'Compound Components',
      lessons: [
        { id: 'les_4', title: 'The Compound Pattern', duration: '15m', completed: true, type: 'video' as const },
        { id: 'les_5', title: 'Context Sharing', duration: '20m', completed: true, type: 'video' as const },
        { id: 'les_6', title: 'Building a Tabs Component', duration: '30m', completed: false, type: 'exercise' as const },
        { id: 'les_7', title: 'Flexible APIs with Slots', duration: '22m', completed: false, type: 'video' as const },
      ],
    },
    {
      id: 'mod_3',
      title: 'Advanced Hooks',
      lessons: [
        { id: 'les_8', title: 'Hook Composition Patterns', duration: '18m', completed: false, type: 'video' as const },
        { id: 'les_9', title: 'State Machines with Hooks', duration: '24m', completed: false, type: 'video' as const },
        { id: 'les_10', title: 'Quiz: Advanced Patterns', duration: '15m', completed: false, type: 'quiz' as const },
      ],
    },
  ],
};

export const mockLeaderboard = [
  { rank: 1, name: 'Emma Watson', xp: 28450, level: 28, avatar: '', streak: 45, badges: 24 },
  { rank: 2, name: 'Liam Chen', xp: 26320, level: 26, avatar: '', streak: 38, badges: 21 },
  { rank: 3, name: 'Sofia Martinez', xp: 25100, level: 25, avatar: '', streak: 52, badges: 19 },
  { rank: 4, name: 'Noah Kim', xp: 23890, level: 24, avatar: '', streak: 30, badges: 18 },
  { rank: 5, name: 'Olivia Brown', xp: 22450, level: 23, avatar: '', streak: 41, badges: 17 },
  { rank: 6, name: 'James Lee', xp: 21200, level: 22, avatar: '', streak: 28, badges: 16 },
  { rank: 7, name: 'Ava Singh', xp: 19800, level: 20, avatar: '', streak: 35, badges: 15 },
  { rank: 8, name: 'Lucas Taylor', xp: 18550, level: 19, avatar: '', streak: 22, badges: 14 },
  { rank: 9, name: 'Mia Johnson', xp: 17200, level: 18, avatar: '', streak: 19, badges: 13 },
  { rank: 10, name: 'Ethan Davis', xp: 16800, level: 17, avatar: '', streak: 26, badges: 12 },
  { rank: 11, name: 'Isabella Wilson', xp: 15400, level: 16, avatar: '', streak: 17, badges: 11 },
  { rank: 42, name: 'Alex Johnson', xp: 12680, level: 12, avatar: '', streak: 14, badges: 6, isCurrentUser: true },
];

export const mockNotifications = [
  { id: 'n1', type: 'achievement' as const, title: 'New Badge Earned!', message: 'You earned the "Fast Learner" badge for completing 5 lessons in one day.', time: '5 min ago', read: false },
  { id: 'n2', type: 'course' as const, title: 'New Course Available', message: '"Full-Stack TypeScript" by Elena Kowalski is now available with early bird pricing.', time: '1 hour ago', read: false },
  { id: 'n3', type: 'social' as const, title: 'Liam Chen followed you', message: 'Liam Chen started following your learning journey.', time: '3 hours ago', read: false },
  { id: 'n4', type: 'streak' as const, title: '14-Day Streak!', message: 'Amazing! You\'ve been learning for 14 days in a row. Keep it up!', time: '6 hours ago', read: true },
  { id: 'n5', type: 'course' as const, title: 'Lesson Updated', message: 'Lesson "Hook Composition Patterns" in Advanced React has been updated.', time: '1 day ago', read: true },
  { id: 'n6', type: 'achievement' as const, title: 'Level Up!', message: 'You reached Level 12! Only 320 XP to the next level.', time: '2 days ago', read: true },
  { id: 'n7', type: 'system' as const, title: 'System Maintenance', message: 'Scheduled maintenance on Saturday 2-4 AM UTC. Some features may be temporarily unavailable.', time: '3 days ago', read: true },
];

export const mockCertificates = [
  { id: 'cert_1', title: 'Advanced React Patterns', instructor: 'Sarah Chen', date: '2025-01-15', courseId: 'cs_1', grade: 'A+' },
  { id: 'cert_2', title: 'UI/UX Design Fundamentals', instructor: 'Marcus Rivera', date: '2024-11-20', courseId: 'cs_2', grade: 'A' },
  { id: 'cert_3', title: 'JavaScript Mastery', instructor: 'Elena Kowalski', date: '2024-09-05', courseId: 'cs_5', grade: 'A+' },
];

export const mockQuizQuestions = [
  {
    id: 'q1',
    question: 'Which React pattern allows a parent component to implicitly share state with its children without passing props?',
    type: 'multiple-choice' as const,
    options: ['Render Props', 'Context API', 'Higher-Order Components', 'Refs'],
    correctAnswer: 1,
    explanation: 'The Context API provides a way to pass data through the component tree without having to pass props down manually at every level.',
  },
  {
    id: 'q2',
    question: 'What is the primary benefit of the Compound Component pattern?',
    type: 'multiple-choice' as const,
    options: [
      'Better performance',
      'Cleaner API surface and flexible composition',
      'Smaller bundle size',
      'Easier state management',
    ],
    correctAnswer: 1,
    explanation: 'Compound Components provide a declarative and flexible API that allows users to compose components in various ways while maintaining implicit state sharing.',
  },
  {
    id: 'q3',
    question: 'In a state machine pattern, what defines all possible states and transitions?',
    type: 'multiple-choice' as const,
    options: ['Reducer function', 'State chart / configuration', 'Context provider', 'Custom hook'],
    correctAnswer: 1,
    explanation: 'A state chart or configuration object explicitly defines all possible states, events, and transitions, making the state logic predictable and visualizable.',
  },
  {
    id: 'q4',
    question: 'Which hook is essential for implementing the "render props" pattern in modern React?',
    type: 'multiple-choice' as const,
    options: ['useEffect', 'useState', 'useMemo', 'Children + cloneElement or render prop functions'],
    correctAnswer: 3,
    explanation: 'Render props typically involve either passing a render function as a prop or using React.Children.map with cloneElement to inject props into children.',
  },
  {
    id: 'q5',
    question: 'What makes a custom hook "composable"?',
    type: 'multiple-choice' as const,
    options: [
      'It can only be used once per component',
      'It can be used inside other hooks to build complex logic from simpler pieces',
      'It must return a JSX element',
      'It requires TypeScript',
    ],
    correctAnswer: 1,
    explanation: 'Composable hooks can call other hooks and be called from within other hooks, allowing you to build complex stateful logic from smaller, reusable pieces.',
  },
];

export const mockFAQs = [
  {
    category: 'General',
    questions: [
      { q: 'What is Lumabela?', a: 'Lumabela is an AI-powered e-learning platform that provides personalized learning experiences for students worldwide. Our AI tutor Lumi adapts to your learning style and pace.' },
      { q: 'How does the AI tutor work?', a: 'Lumi analyzes your learning patterns, strengths, and areas for improvement to provide personalized explanations, practice problems, and study recommendations.' },
      { q: 'Is Lumabela free to use?', a: 'Lumabela offers both free and premium plans. The free plan includes access to basic courses and limited AI features. Premium unlocks all content and advanced AI capabilities.' },
    ],
  },
  {
    category: 'Courses & Learning',
    questions: [
      { q: 'How are courses structured?', a: 'Each course is divided into modules containing video lessons, interactive exercises, quizzes, and hands-on projects. You learn at your own pace with progress tracking.' },
      { q: 'Can I get certificates?', a: 'Yes! Upon completing a course and passing the final assessment, you receive a verifiable digital certificate that you can share on LinkedIn and other platforms.' },
      { q: 'How long do I have access to a course?', a: 'Once enrolled, you have lifetime access to the course content, including any future updates made by the instructor.' },
    ],
  },
  {
    category: 'Premium & Billing',
    questions: [
      { q: 'What does Premium include?', a: 'Premium includes unlimited access to all courses, advanced AI tutoring, priority support, offline downloads, certificates, and ad-free experience.' },
      { q: 'Can I cancel anytime?', a: 'Yes, you can cancel your Premium subscription at any time. You\'ll continue to have access until the end of your billing period.' },
      { q: 'Do you offer student discounts?', a: 'Yes! We offer 50% off Premium for verified students with a valid .edu email address.' },
    ],
  },
  {
    category: 'Technical',
    questions: [
      { q: 'What devices are supported?', a: 'Lumabela works on all modern browsers, desktop and mobile. We also have progressive web app support for offline learning.' },
      { q: 'Is my data secure?', a: 'Absolutely. We use industry-standard encryption, regular security audits, and never sell your personal data to third parties.' },
    ],
  },
];

export const weeklyProgress = [
  { day: 'Mon', xp: 120, minutes: 45 },
  { day: 'Tue', xp: 85, minutes: 30 },
  { day: 'Wed', xp: 200, minutes: 75 },
  { day: 'Thu', xp: 150, minutes: 55 },
  { day: 'Fri', xp: 180, minutes: 65 },
  { day: 'Sat', xp: 250, minutes: 90 },
  { day: 'Sun', xp: 95, minutes: 35 },
];